### ISSUE TITLE
gestion des exceptions, du routing

### ISSUE THREAD

**Issue by omansour** [M6Web/PhpProcessManagerBundle#7]
je n'arrive pas à faire marcher une application de test et lancer une 404 

je rentre toujours là dedans https://github.com/M6Web/PhpProcessManagerBundle/blob/master/Bridge/HttpKernel.php#L57 avec une InvalidArgumentException - "Type is not supported".

**Comment by fabdsp** [comment]
@omansour trouvé, c'est un problème totalement à part : c'est le json_encode qui retourne cette erreur car la stack trace a une référence récursive (!!!). On va ajouter quelque chose pour limiter ce cas dans le bundle exception. En prod le problème n'y est pas donc.

**Comment by omansour** [comment]
:+1:

**Comment by fabdsp** [comment]
https://github.com/M6Web/ApiExceptionBundle/pull/7
